### ISSUE TITLE
More README info please

### ISSUE THREAD

**Issue by E3V3A** [moiji-mobile/diag-parser#1]
Cool project, and thanks for taking time to simplify these things. 
1. Can you please write a few lines on the underlying dependencies, especially details regarding the `build_local.sh`?
2. How do you run it and can you post some examples + screen shots?
3. The command options are not very clear, e.g.:

``` bash
./diag_import -g A.B.C.D -p local_file.pcap -i /dev/ttyUSB0
```
- a) What is on that USB bus? 
- b) Are these the Qualcomm DIAG ports that gets enumerated when connecting to a phone, for example?

**Comment by zecke** [comment]
- build_local.sh: Have a look but I mentioned libosmocore.
- Open pcap file in wireshark
- Added short help text to README.md but -h should explain it
- /dev/ttyUSB0 is the first interface that enumerates for UC20/EC20 and is the DIAG port
- Depends on your phone and its bus config.
