### ISSUE TITLE
Incomplete traces and abnormal exit 

### ISSUE THREAD

**Issue by pcabreracamara** [moiji-mobile/diag-parser#4]
Hi,

I have been playing with Quectel EC20 modem on APU2C4 runing Ubuntu 16.04 and diag-parser tool, but looks like something is going bad as;

- From time to time "diag-parser" tool stop suddenly, no error code, core dump or log, just stop.
- When I analyze the PCAP files, only see one or two messages without any sense. i.e; the last session I connect to 2G network, browse some webs and recive two calls. In the PCAP file there is only "Authentication Response" and "Call Confirmed" messages:

![image](https://cloud.githubusercontent.com/assets/8314063/22509143/12e31604-e88d-11e6-8527-f5329e2a8b39.png)

Are there any troubleshoouting comands to check what is the problem? I check with QMI commands the connection, cellID, modem state and everything is ok.

Thank you very much for your help,
Pedro

**Comment by zecke** [comment]
Could you see with dmesg if the USB devices re-enumerated? If reading fails (once) the application will exit. I think this might happen here? Could you use gdb and set a breakpoint in abort and exit and then check who is calling it?

Hmm. didn't see it that yet. If you can reproduce it we can compare what is read to what is there.

In general this tool is/will be obsoleted by https://git.osmocom.org/osmo-qcdiag/

**Comment by pcabreracamara** [comment]
This is what I found on dmesg regarding qmi_wwan, it is renamed at the end:

```
[    6.376443] qmi_wwan 1-1.3:1.4: cdc-wdm0: USB WDM device
[    6.377332] qmi_wwan 1-1.3:1.4 wwan0: register 'qmi_wwan' at usb-0000:00:13.0-1.3, WWAN/QMI device, 8e:88:75:aa:ed:c4
[    6.377439] usbcore: registered new interface driver qmi_wwan
[    7.012945] qmi_wwan 1-1.3:1.4 wwp0s19u1u3i4: renamed from wwan0
```

I set up the breakpoints with no luck (not abnormal exit), I will try more times. In the last test, I saw some code in the same time I was calling a number (diag_parser was running on background):

```
/opt/diag-parser# echo -e "ATD...\r\n" > /dev/ttyUSB2
/opt/diag-parser# GSM CS UL 534983 : 010329e797ef8e1900000000062b2b2b2b2b2b2b2b2b2b
```

But again, in PCAP there are only two lines, and this last message is "Unknown":
![image](https://cloud.githubusercontent.com/assets/8314063/22529037/129ec79e-e8d6-11e6-941f-62d6ea5474ad.png)

**Comment by pcabreracamara** [comment]
Hi,

I'm sorry to come back so late, the issue can be closed.

- Abnormal exits has nothing to be related with diag-parser (OS related).

- Incomplete traces; I clone and compile by my own libosmocore and osmo-qcdiag. From that point I see all traces from diag-parser completes.

Thank you very much,
Pedro
